### ISSUE TITLE
fix(Attribute Flex): flex-shrink & flex-grow

### ISSUE THREAD

**Issue by dapize** [dapize/layouter#53]
Cuando se declara el 'fh'(flex-shrink) y 'fg' (flex-grow) en conjunto a cualquier otra designación como 'jc:ce' (justify-content:center), no se llega a declarar en los estilos resultantes el 'display: flex' debido a la restricción propia del 'fh y fg'.

```html
<div flex="fh:0 jc:ce"></div>
```
resulta:

```html
<div class="flex-fh:0-jc:ce@xs"></div>
```

```css
.flex-fh\:0-jc\:ce\@xs {
    flex-shrink: 0;
    justify-content: center;
}
```
